# Generated by Django 2.0.7 on 2019-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.TextField(default=None),
        ),
    ]
