# Generated by Django 2.0.7 on 2019-06-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_item_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Daiktas', 'verbose_name_plural': 'Daiktai'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='state',
        ),
    ]
