# Generated by Django 2.2.2 on 2019-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20190608_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='defaultslug'),
            preserve_default=False,
        ),
    ]
