# Generated by Django 2.2.2 on 2019-06-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_item_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
            ],
            options={
                'verbose_name': 'Daikto Tipas',
                'verbose_name_plural': 'Daikto Tipai',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ItemType'),
        ),
    ]
