# Generated by Django 2.2.2 on 2019-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190608_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
