# Generated by Django 2.2.2 on 2019-06-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_itemtype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Daikto Buklė',
                'verbose_name_plural': 'Daiktų Buklė',
            },
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'Daikto Tipas', 'verbose_name_plural': 'Daiktų Tipai'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ItemType', verbose_name='Tipas'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ItemCondition', verbose_name='Būklė'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(verbose_name='Nuorodos pavadinimas'),
        ),
    ]
