# Generated by Django 2.0.7 on 2019-06-09 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0010_auto_20190609_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Veiksmas')),
                ('date', models.DateTimeField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Žurnalas',
            },
        ),
        migrations.DeleteModel(
            name='ItemCondition',
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='log',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Item'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
