# Generated by Django 2.0.7 on 2019-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20190609_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=150, verbose_name='Veiksmas'),
        ),
    ]
