# Generated by Django 2.0.7 on 2019-06-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20190609_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Veiksmas', 'verbose_name_plural': 'Žurnalas'},
        ),
    ]
